# Generated by Django 2.1.7 on 2019-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '01_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('paginas', models.IntegerField()),
            ],
            options={
                'db_table': 'livro',
            },
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='cesta',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='loja',
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='Cesta',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
